# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.search_prodName_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.search_prodName_lineEdit.setObjectName("search_prodName_lineEdit")
        self.horizontalLayout.addWidget(self.search_prodName_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.from_dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.from_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.from_dateEdit.setObjectName("from_dateEdit")
        self.horizontalLayout_2.addWidget(self.from_dateEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.to_dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.to_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.to_dateEdit.setObjectName("to_dateEdit")
        self.horizontalLayout_2.addWidget(self.to_dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.search_prodName_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.search_prodName_pushButton.setObjectName("search_prodName_pushButton")
        self.horizontalLayout_3.addWidget(self.search_prodName_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.contracts_listWidget = QtWidgets.QListWidget(self.groupBox)
        self.contracts_listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contracts_listWidget.setAlternatingRowColors(True)
        self.contracts_listWidget.setWordWrap(True)
        self.contracts_listWidget.setObjectName("contracts_listWidget")
        self.verticalLayout.addWidget(self.contracts_listWidget)
        self.year_price_qlabel = QtWidgets.QLabel(self.groupBox)
        self.year_price_qlabel.setText("")
        self.year_price_qlabel.setObjectName("year_price_qlabel")
        self.verticalLayout.addWidget(self.year_price_qlabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.summary_textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.summary_textBrowser.setObjectName("summary_textBrowser")
        self.gridLayout.addWidget(self.summary_textBrowser, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.save_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.save_pushButton.setObjectName("save_pushButton")
        self.verticalLayout_2.addWidget(self.save_pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Поиск по наименованию продукта"))
        self.label_3.setText(_translate("MainWindow", "Наименование:"))
        self.search_prodName_lineEdit.setText(_translate("MainWindow", "Формалин"))
        self.label.setText(_translate("MainWindow", "Временной период:"))
        self.label_2.setText(_translate("MainWindow", "-"))
        self.search_prodName_pushButton.setText(_translate("MainWindow", "Поиск"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Превью данных"))
        self.save_pushButton.setText(_translate("MainWindow", "Сохранить"))

